_target_: src.models.message_event_encoder.MessageEventEncoderLitModule

vector_size: ${vocab_size}
hidden_size: ${embedded_size}
max_length: ${max_message_length}

START:
    _target_: torch.LongTensor
    data: ${start:${vocab_size}}

END:
    _target_: torch.LongTensor
    data: ${end:${vocab_size}}

optimizer: 
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0001
