_target_: src.models.sequence_rnn.SequenceRNN

embedding_size: ???
embedding_dimension: ???
max_length: ???

optimizer: 
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0001

tf_rate: 0.8

